namespace:
  name: prod
image:
  repository: sumitkumarsingh/techtrends
  tag: latest
  imagePullPolicy: Always
service:
  port:7111

replicaCount: 5
resources:
  requests:
    cpu: 350m
    memory: 128Mi
