namespace:
  name: staging
image:
  repository: sumitkumarsingh/techtrends
  tag: latest

service:
  port:5111

replicaCount: 3
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 300m
    memory: 90Mi
